- name: create Minecraft group
  group:
    state: present
    name: "{{ minecraft_group }}"
    system: yes

- name: create Minecraft user
  user:
    state: present
    name: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
    home: "{{ minecraft_home }}"

- name: create Spigot build directory
  file:
    path: "{{ minecraft_home }}/build"
    state: directory
    mode: 0755
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"

- name: download Spigot build tools
  get_url:
    url: "{{ minecraft_spigot_url }}"
    dest: "{{ minecraft_home }}/build"
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
    mode: 0755

- name: build Spigot server
  command: java -jar BuildTools.jar --rev "{{ minecraft_version_latest | default(minecraft_version) }}"
  args:
    creates: spigot-{{ minecraft_version_latest | default(minecraft_version) }}.jar
    chdir: "{{ minecraft_home }}/build"
  environment:
    SHELL: /bin/bash

- name: symlink Spigot server
  file:
    src: "{{ minecraft_home }}/build/spigot-{{ minecraft_version_latest | default(minecraft_version) }}.jar"
    path: "{{ minecraft_home }}/spigot.jar"
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
    state: link
